plugins:
  mcn-org/test-repo:
    - approve  # Allow OWNERS to /approve
    - assign  # Allow /assign and /cc
    - blunderbuss  # Auto-assign people
    - help  # Support /help and /good-first-issue
    - hold  # Support /hold to delay merge
    - lgtm  # Allow /lgtm
    - lifecycle  # Allow /lifecycle stale
    - override
    - stage
    - label
    - docs-no-retest
    - size  # Auto-label size of PR
    - trigger  # Allow people to configure CI jobs to /test
    - verify-owners # Validates OWNERS file changes in PRs.
    - wip  # Auto-hold PRs with WIP in title
    - yuks # Let prow tell a /joke

welcome:
  - repos:
      - mcn-org/test-repo
    message_template: "Welcome @{{.AuthorLogin}}! <br><br>It looks like this is your first PR to <a href='https://github.com/{{.Org}}/{{.Repo}}'>{{.Org}}/{{.Repo}}</a> 🎉. Please refer to our [pull request process documentation](https://git.k8s.io/community/contributors/guide/pull-requests.md) to help your PR have a smooth ride to approval. <br><br>You will be prompted by a bot to use commands during the review process. Do not be afraid to follow the prompts! It is okay to experiment. [Here is the bot commands documentation](http://msn.ci.netwiz.org/bot-commands). <br><br>You can also check if {{.Org}}/{{.Repo}} has [its own contribution guidelines](https://github.com/{{.Org}}/{{.Repo}}/tree/master/CONTRIBUTING.md). <br><br>You may want to refer to our [testing guide](https://git.k8s.io/community/contributors/devel/sig-testing/testing.md) if you run into trouble with your tests not passing. <br><br>If you are having difficulty getting your pull request seen, please follow the [recommended escalation practices](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#why-is-my-pull-request-not-getting-reviewed). Also, for tips and tricks in the contribution process you may want to read the [Kubernetes contributor cheat sheet](https://git.k8s.io/community/contributors/guide/contributor-cheatsheet/README.md). We want to make sure your contribution gets all the attention it needs! <br><br>Thank you, and welcome to Kubernetes. :smiley:"

blunderbuss:
  max_request_count: 2
  use_status_availability: true

lgtm:
  - repos:
      - mcn-org/test-repo
    review_acts_as_lgtm: true

approve:
  - repos:
      - mcn-org/test-repo
    require_self_approval: false
    lgtm_acts_as_approve: true

external_plugins:
  mcn-org/test-repo:
    - name: needs-rebase
      events:
        - pull_request

require_matching_label:
  - missing_label: needs-kind
    org: mcn-org
    repo: test-repo
    prs: true
    regexp: ^kind/
  - missing_label: needs-sig
    org: mcn-org
    repo: test-repo
    prs: true
    regexp: ^(sig|wg|committee)/
    missing_comment: |
      There are no sig labels on this issue. Please add a sig label by either:
      1. mentioning a sig: `@kubernetes/sig-<group-name>-<group-suffix>`
          e.g., `@kubernetes/sig-contributor-experience-<group-suffix>` to notify the contributor experience sig, OR
      2. specifying the label manually: `/sig <group-name>`
          e.g., `/sig scalability` to apply the `sig/scalability` label
      Note: Method 1 will trigger an email to the group. See the [group list](https://git.k8s.io/community/sig-list.md).
      The `<group-suffix>` in method 1 has to be replaced with one of these: _**bugs, feature-requests, pr-reviews, test-failures, proposals**_.